services:
#  nginx_proxy:
#    image: nginx:latest
#    container_name: meridian_reverse_proxy
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - messaging
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: meridian_zookeeper
    networks:
      - meridian_network
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    restart: unless-stopped
  kafka:
    image: bitnami/kafka:latest
    container_name: meridian_kafka
    networks:
      - meridian_network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller # Run as both broker and controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
  messaging_postgres:
    image: postgres:alpine
    container_name: meridian_postgres_messaging
    environment:
      POSTGRES_USER: ${MESSAGING_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MESSAGING_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MESSAGING_DB_NAME}
    networks:
      - meridian_network
    volumes:
      - messaging_postgres_data:/var/lib/postgresql/data
    ports:
      - "${MESSAGING_DB_PORT}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${MESSAGING_POSTGRES_USER} -d ${MESSAGING_DB_NAME}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  messaging_redis:
    image: redis:7-alpine
    container_name: meridian_redis_messaging
    command: --port ${MESSAGING_REDIS_PORT}
    networks:
      - meridian_network
    ports:
      - "${MESSAGING_REDIS_PORT}:${MESSAGING_REDIS_PORT}"
    restart: unless-stopped
  messaging_migrate:
    build:
      context: ../
      dockerfile: deployments/migrate/Dockerfile
    container_name: meridian_messaging_migrate
    networks:
      - meridian_network
    depends_on:
      messaging_postgres:
        condition: service_healthy
    volumes:
      - ../internal/messaging/infrastructure/persistence/migrations:/migrations
    environment:
      MIGRATE_DB_URL_MIGRATE: "${MESSAGING_DB_URL_MIGRATE}"
    command:
      ["-path", "/migrations", "-database", "${MESSAGING_DB_URL_MIGRATE}", "up"]
  messaging:
    build:
      context: ../
      dockerfile: deployments/messaging/Dockerfile
    container_name: meridian_messaging_service
    depends_on:
      messaging_migrate:
        condition: service_completed_successfully
      messaging_postgres:
        condition: service_healthy
      messaging_redis:
        condition: service_started
    environment:
      MESSAGING_DB_URL: "${MESSAGING_DB_URL}"
      MESSAGING_HTTP_PORT: ":${MESSAGING_HTTP_PORT}"
      MESSAGING_KAFKA_BROKERS: "${KAFKA_BROKERS}"
      MESSAGING_KAFKA_DEFAULT_TOPIC: "${MESSAGING_KAFKA_DEFAULT_TOPIC}"
    networks:
      - meridian_network
    ports:
      - "${MESSAGING_HTTP_PORT}:${MESSAGING_HTTP_PORT}"
    restart: unless-stopped
  identity_postgres:
    image: postgres:alpine
    container_name: meridian_postgres_identity
    environment:
      POSTGRES_USER: "${IDENTITY_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${IDENTITY_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${IDENTITY_DB_NAME}"
    networks:
      - meridian_network
    volumes:
      - identity_postgres_data:/var/lib/postgresql/data
    ports:
      - "${IDENTITY_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${IDENTITY_POSTGRES_USER} -d ${IDENTITY_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  identity_migrate:
    build:
      context: ../
      dockerfile: deployments/migrate/Dockerfile
    container_name: meridian_identity_migrate
    networks:
      - meridian_network
    depends_on:
      identity_postgres:
        condition: service_healthy
    volumes:
      - ../internal/identity/infrastructure/persistence/migrations:/migrations
    environment:
      MIGRATE_DB_URL_MIGRATE: "${IDENTITY_DB_URL_MIGRATE}"
    command:
      ["-path", "/migrations", "-database", "${IDENTITY_DB_URL_MIGRATE}", "up"]
  identity:
    build:
      context: ../
      dockerfile: deployments/identity/Dockerfile
    container_name: meridian_identity_service
    networks:
      - meridian_network
    depends_on:
      identity_migrate:
        condition: service_completed_successfully
      identity_postgres:
        condition: service_healthy
    environment:
      IDENTITY_HTTP_PORT: ":${IDENTITY_HTTP_PORT}"
      IDENTITY_DB_URL: "${IDENTITY_DB_URL}"
      IDENTITY_KAFKA_BROKERS: "${KAFKA_BROKERS}"
      IDENTITY_KAFKA_DEFAULT_TOPIC: "${IDENTITY_KAFKA_DEFAULT_TOPIC}"
      IDENTITY_PASETO_PRIVATE_KEY: "${IDENTITY_PASETO_PRIVATE_KEY}"
      IDENTITY_PASETO_PUBLIC_KEY: "${IDENTITY_PASETO_PUBLIC_KEY}"
      AUTH_TOKEN_VALIDITY_MINUTES: "${AUTH_TOKEN_VALIDITY_MINUTES}"
    ports:
      - "${IDENTITY_HTTP_PORT}:${IDENTITY_HTTP_PORT}"
    restart: unless-stopped

networks:
  meridian_network:
    driver: bridge
volumes:
  messaging_postgres_data:
  identity_postgres_data:
  zookeeper_data:
  kafka_data:
