// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/messaging/infrastructure/api/messaging.proto

package messagingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	SenderId         string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderType       string                 `protobuf:"bytes,3,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"` // "user" or "integration"
	SenderName       string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	TargetChannelIds []string               `protobuf:"bytes,5,rep,name=target_channel_ids,json=targetChannelIds,proto3" json:"target_channel_ids,omitempty"`
	MessageType      string                 `protobuf:"bytes,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // "direct", "integration_webhook", etc.
	Metadata         map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderType() string {
	if x != nil {
		return x.SenderType
	}
	return ""
}

func (x *SendMessageRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SendMessageRequest) GetTargetChannelIds() []string {
	if x != nil {
		return x.TargetChannelIds
	}
	return nil
}

func (x *SendMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *SendMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MessageId        string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageContent   string                 `protobuf:"bytes,4,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	TargetChannelIds []string               `protobuf:"bytes,5,rep,name=target_channel_ids,json=targetChannelIds,proto3" json:"target_channel_ids,omitempty"`
	SenderId         string                 `protobuf:"bytes,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderType       string                 `protobuf:"bytes,7,opt,name=sender_type,json=senderType,proto3" json:"sender_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageResponse) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *MessageResponse) GetTargetChannelIds() []string {
	if x != nil {
		return x.TargetChannelIds
	}
	return nil
}

func (x *MessageResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageResponse) GetSenderType() string {
	if x != nil {
		return x.SenderType
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Responses     []*MessageResponse     `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetResponses() []*MessageResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetMessagesRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{6}
}

func (x *GetMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Message struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId       string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderUserId    string                 `protobuf:"bytes,3,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	IntegrationId   string                 `protobuf:"bytes,4,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	Content         *MessageContent        `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ParentMessageId string                 `protobuf:"bytes,7,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	Reactions       []*Reaction            `protobuf:"bytes,8,rep,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Message) GetSenderUserId() string {
	if x != nil {
		return x.SenderUserId
	}
	return ""
}

func (x *Message) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *Message) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Message) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *Message) GetReactions() []*Reaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Mentions      []string               `protobuf:"bytes,2,rep,name=mentions,proto3" json:"mentions,omitempty"`
	Links         []string               `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	Formatted     bool                   `protobuf:"varint,4,opt,name=formatted,proto3" json:"formatted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{8}
}

func (x *MessageContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageContent) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *MessageContent) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MessageContent) GetFormatted() bool {
	if x != nil {
		return x.Formatted
	}
	return false
}

type Reaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReactionType  string                 `protobuf:"bytes,4,opt,name=reaction_type,json=reactionType,proto3" json:"reaction_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_messaging_infrastructure_api_messaging_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP(), []int{9}
}

func (x *Reaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reaction) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Reaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reaction) GetReactionType() string {
	if x != nil {
		return x.ReactionType
	}
	return ""
}

func (x *Reaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_internal_messaging_infrastructure_api_messaging_proto protoreflect.FileDescriptor

const file_internal_messaging_infrastructure_api_messaging_proto_rawDesc = "" +
	"\n" +
	"5internal/messaging/infrastructure/api/messaging.proto\x12\fmessaging.v1\"\xe7\x02\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_type\x18\x03 \x01(\tR\n" +
	"senderType\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12,\n" +
	"\x12target_channel_ids\x18\x05 \x03(\tR\x10targetChannelIds\x12!\n" +
	"\fmessage_type\x18\x06 \x01(\tR\vmessageType\x12J\n" +
	"\bmetadata\x18\a \x03(\v2..messaging.v1.SendMessageRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x01\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12'\n" +
	"\x0fmessage_content\x18\x04 \x01(\tR\x0emessageContent\x12,\n" +
	"\x12target_channel_ids\x18\x05 \x03(\tR\x10targetChannelIds\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_type\x18\a \x01(\tR\n" +
	"senderType\"l\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12;\n" +
	"\tresponses\x18\x02 \x03(\v2\x1d.messaging.v1.MessageResponseR\tresponses\"~\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\"i\n" +
	"\x13GetMessagesResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.messaging.v1.MessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"2\n" +
	"\x11GetMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"E\n" +
	"\x12GetMessageResponse\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.messaging.v1.MessageR\amessage\"\xbe\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12$\n" +
	"\x0esender_user_id\x18\x03 \x01(\tR\fsenderUserId\x12%\n" +
	"\x0eintegration_id\x18\x04 \x01(\tR\rintegrationId\x126\n" +
	"\acontent\x18\x05 \x01(\v2\x1c.messaging.v1.MessageContentR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12*\n" +
	"\x11parent_message_id\x18\a \x01(\tR\x0fparentMessageId\x124\n" +
	"\treactions\x18\b \x03(\v2\x16.messaging.v1.ReactionR\treactions\"t\n" +
	"\x0eMessageContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\bmentions\x18\x02 \x03(\tR\bmentions\x12\x14\n" +
	"\x05links\x18\x03 \x03(\tR\x05links\x12\x1c\n" +
	"\tformatted\x18\x04 \x01(\bR\tformatted\"\x96\x01\n" +
	"\bReaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rreaction_type\x18\x04 \x01(\tR\freactionType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\x8b\x02\n" +
	"\x10MessagingService\x12R\n" +
	"\vSendMessage\x12 .messaging.v1.SendMessageRequest\x1a!.messaging.v1.SendMessageResponse\x12R\n" +
	"\vGetMessages\x12 .messaging.v1.GetMessagesRequest\x1a!.messaging.v1.GetMessagesResponse\x12O\n" +
	"\n" +
	"GetMessage\x12\x1f.messaging.v1.GetMessageRequest\x1a .messaging.v1.GetMessageResponseBUZSgithub.com/m1thrandir225/meridian/internal/messaging/infrastructure/api;messagingpbb\x06proto3"

var (
	file_internal_messaging_infrastructure_api_messaging_proto_rawDescOnce sync.Once
	file_internal_messaging_infrastructure_api_messaging_proto_rawDescData []byte
)

func file_internal_messaging_infrastructure_api_messaging_proto_rawDescGZIP() []byte {
	file_internal_messaging_infrastructure_api_messaging_proto_rawDescOnce.Do(func() {
		file_internal_messaging_infrastructure_api_messaging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_messaging_infrastructure_api_messaging_proto_rawDesc), len(file_internal_messaging_infrastructure_api_messaging_proto_rawDesc)))
	})
	return file_internal_messaging_infrastructure_api_messaging_proto_rawDescData
}

var file_internal_messaging_infrastructure_api_messaging_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_messaging_infrastructure_api_messaging_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: messaging.v1.SendMessageRequest
	(*MessageResponse)(nil),     // 1: messaging.v1.MessageResponse
	(*SendMessageResponse)(nil), // 2: messaging.v1.SendMessageResponse
	(*GetMessagesRequest)(nil),  // 3: messaging.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil), // 4: messaging.v1.GetMessagesResponse
	(*GetMessageRequest)(nil),   // 5: messaging.v1.GetMessageRequest
	(*GetMessageResponse)(nil),  // 6: messaging.v1.GetMessageResponse
	(*Message)(nil),             // 7: messaging.v1.Message
	(*MessageContent)(nil),      // 8: messaging.v1.MessageContent
	(*Reaction)(nil),            // 9: messaging.v1.Reaction
	nil,                         // 10: messaging.v1.SendMessageRequest.MetadataEntry
}
var file_internal_messaging_infrastructure_api_messaging_proto_depIdxs = []int32{
	10, // 0: messaging.v1.SendMessageRequest.metadata:type_name -> messaging.v1.SendMessageRequest.MetadataEntry
	1,  // 1: messaging.v1.SendMessageResponse.responses:type_name -> messaging.v1.MessageResponse
	7,  // 2: messaging.v1.GetMessagesResponse.messages:type_name -> messaging.v1.Message
	7,  // 3: messaging.v1.GetMessageResponse.message:type_name -> messaging.v1.Message
	8,  // 4: messaging.v1.Message.content:type_name -> messaging.v1.MessageContent
	9,  // 5: messaging.v1.Message.reactions:type_name -> messaging.v1.Reaction
	0,  // 6: messaging.v1.MessagingService.SendMessage:input_type -> messaging.v1.SendMessageRequest
	3,  // 7: messaging.v1.MessagingService.GetMessages:input_type -> messaging.v1.GetMessagesRequest
	5,  // 8: messaging.v1.MessagingService.GetMessage:input_type -> messaging.v1.GetMessageRequest
	2,  // 9: messaging.v1.MessagingService.SendMessage:output_type -> messaging.v1.SendMessageResponse
	4,  // 10: messaging.v1.MessagingService.GetMessages:output_type -> messaging.v1.GetMessagesResponse
	6,  // 11: messaging.v1.MessagingService.GetMessage:output_type -> messaging.v1.GetMessageResponse
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_messaging_infrastructure_api_messaging_proto_init() }
func file_internal_messaging_infrastructure_api_messaging_proto_init() {
	if File_internal_messaging_infrastructure_api_messaging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_messaging_infrastructure_api_messaging_proto_rawDesc), len(file_internal_messaging_infrastructure_api_messaging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_messaging_infrastructure_api_messaging_proto_goTypes,
		DependencyIndexes: file_internal_messaging_infrastructure_api_messaging_proto_depIdxs,
		MessageInfos:      file_internal_messaging_infrastructure_api_messaging_proto_msgTypes,
	}.Build()
	File_internal_messaging_infrastructure_api_messaging_proto = out.File
	file_internal_messaging_infrastructure_api_messaging_proto_goTypes = nil
	file_internal_messaging_infrastructure_api_messaging_proto_depIdxs = nil
}
