// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/integration/infrastructure/api/integration.proto

package integrationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAPITokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAPITokenRequest) Reset() {
	*x = ValidateAPITokenRequest{}
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPITokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPITokenRequest) ProtoMessage() {}

func (x *ValidateAPITokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPITokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateAPITokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_integration_infrastructure_api_integration_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAPITokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateAPITokenResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Valid           bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	IntegrationId   string                 `protobuf:"bytes,2,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	IntegrationName string                 `protobuf:"bytes,3,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateAPITokenResponse) Reset() {
	*x = ValidateAPITokenResponse{}
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAPITokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAPITokenResponse) ProtoMessage() {}

func (x *ValidateAPITokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAPITokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateAPITokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_integration_infrastructure_api_integration_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAPITokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAPITokenResponse) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *ValidateAPITokenResponse) GetIntegrationName() string {
	if x != nil {
		return x.IntegrationName
	}
	return ""
}

func (x *ValidateAPITokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntegrationId string                 `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationRequest) Reset() {
	*x = GetIntegrationRequest{}
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationRequest) ProtoMessage() {}

func (x *GetIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_internal_integration_infrastructure_api_integration_proto_rawDescGZIP(), []int{2}
}

func (x *GetIntegrationRequest) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

type GetIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integration   *Integration           `protobuf:"bytes,1,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationResponse) Reset() {
	*x = GetIntegrationResponse{}
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationResponse) ProtoMessage() {}

func (x *GetIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_internal_integration_infrastructure_api_integration_proto_rawDescGZIP(), []int{3}
}

func (x *GetIntegrationResponse) GetIntegration() *Integration {
	if x != nil {
		return x.Integration
	}
	return nil
}

type Integration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceName      string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CreatorUserId    string                 `protobuf:"bytes,3,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id,omitempty"`
	HashedApiToken   string                 `protobuf:"bytes,4,opt,name=hashed_api_token,json=hashedApiToken,proto3" json:"hashed_api_token,omitempty"`
	TokenLookupHash  string                 `protobuf:"bytes,5,opt,name=token_lookup_hash,json=tokenLookupHash,proto3" json:"token_lookup_hash,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsRevoked        bool                   `protobuf:"varint,7,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	TargetChannelIds []string               `protobuf:"bytes,8,rep,name=target_channel_ids,json=targetChannelIds,proto3" json:"target_channel_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Integration) Reset() {
	*x = Integration{}
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integration) ProtoMessage() {}

func (x *Integration) ProtoReflect() protoreflect.Message {
	mi := &file_internal_integration_infrastructure_api_integration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integration.ProtoReflect.Descriptor instead.
func (*Integration) Descriptor() ([]byte, []int) {
	return file_internal_integration_infrastructure_api_integration_proto_rawDescGZIP(), []int{4}
}

func (x *Integration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Integration) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Integration) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *Integration) GetHashedApiToken() string {
	if x != nil {
		return x.HashedApiToken
	}
	return ""
}

func (x *Integration) GetTokenLookupHash() string {
	if x != nil {
		return x.TokenLookupHash
	}
	return ""
}

func (x *Integration) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Integration) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

func (x *Integration) GetTargetChannelIds() []string {
	if x != nil {
		return x.TargetChannelIds
	}
	return nil
}

var File_internal_integration_infrastructure_api_integration_proto protoreflect.FileDescriptor

const file_internal_integration_infrastructure_api_integration_proto_rawDesc = "" +
	"\n" +
	"9internal/integration/infrastructure/api/integration.proto\x12\x0eintegration.v1\"/\n" +
	"\x17ValidateAPITokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x98\x01\n" +
	"\x18ValidateAPITokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12%\n" +
	"\x0eintegration_id\x18\x02 \x01(\tR\rintegrationId\x12)\n" +
	"\x10integration_name\x18\x03 \x01(\tR\x0fintegrationName\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\">\n" +
	"\x15GetIntegrationRequest\x12%\n" +
	"\x0eintegration_id\x18\x01 \x01(\tR\rintegrationId\"W\n" +
	"\x16GetIntegrationResponse\x12=\n" +
	"\vintegration\x18\x01 \x01(\v2\x1b.integration.v1.IntegrationR\vintegration\"\xaa\x02\n" +
	"\vIntegration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12&\n" +
	"\x0fcreator_user_id\x18\x03 \x01(\tR\rcreatorUserId\x12(\n" +
	"\x10hashed_api_token\x18\x04 \x01(\tR\x0ehashedApiToken\x12*\n" +
	"\x11token_lookup_hash\x18\x05 \x01(\tR\x0ftokenLookupHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\a \x01(\bR\tisRevoked\x12,\n" +
	"\x12target_channel_ids\x18\b \x03(\tR\x10targetChannelIds2\xdc\x01\n" +
	"\x12IntegrationService\x12e\n" +
	"\x10ValidateAPIToken\x12'.integration.v1.ValidateAPITokenRequest\x1a(.integration.v1.ValidateAPITokenResponse\x12_\n" +
	"\x0eGetIntegration\x12%.integration.v1.GetIntegrationRequest\x1a&.integration.v1.GetIntegrationResponseBYZWgithub.com/m1thrandir225/meridian/internal/integration/infrastructure/api;integrationpbb\x06proto3"

var (
	file_internal_integration_infrastructure_api_integration_proto_rawDescOnce sync.Once
	file_internal_integration_infrastructure_api_integration_proto_rawDescData []byte
)

func file_internal_integration_infrastructure_api_integration_proto_rawDescGZIP() []byte {
	file_internal_integration_infrastructure_api_integration_proto_rawDescOnce.Do(func() {
		file_internal_integration_infrastructure_api_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_integration_infrastructure_api_integration_proto_rawDesc), len(file_internal_integration_infrastructure_api_integration_proto_rawDesc)))
	})
	return file_internal_integration_infrastructure_api_integration_proto_rawDescData
}

var file_internal_integration_infrastructure_api_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_integration_infrastructure_api_integration_proto_goTypes = []any{
	(*ValidateAPITokenRequest)(nil),  // 0: integration.v1.ValidateAPITokenRequest
	(*ValidateAPITokenResponse)(nil), // 1: integration.v1.ValidateAPITokenResponse
	(*GetIntegrationRequest)(nil),    // 2: integration.v1.GetIntegrationRequest
	(*GetIntegrationResponse)(nil),   // 3: integration.v1.GetIntegrationResponse
	(*Integration)(nil),              // 4: integration.v1.Integration
}
var file_internal_integration_infrastructure_api_integration_proto_depIdxs = []int32{
	4, // 0: integration.v1.GetIntegrationResponse.integration:type_name -> integration.v1.Integration
	0, // 1: integration.v1.IntegrationService.ValidateAPIToken:input_type -> integration.v1.ValidateAPITokenRequest
	2, // 2: integration.v1.IntegrationService.GetIntegration:input_type -> integration.v1.GetIntegrationRequest
	1, // 3: integration.v1.IntegrationService.ValidateAPIToken:output_type -> integration.v1.ValidateAPITokenResponse
	3, // 4: integration.v1.IntegrationService.GetIntegration:output_type -> integration.v1.GetIntegrationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_integration_infrastructure_api_integration_proto_init() }
func file_internal_integration_infrastructure_api_integration_proto_init() {
	if File_internal_integration_infrastructure_api_integration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_integration_infrastructure_api_integration_proto_rawDesc), len(file_internal_integration_infrastructure_api_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_integration_infrastructure_api_integration_proto_goTypes,
		DependencyIndexes: file_internal_integration_infrastructure_api_integration_proto_depIdxs,
		MessageInfos:      file_internal_integration_infrastructure_api_integration_proto_msgTypes,
	}.Build()
	File_internal_integration_infrastructure_api_integration_proto = out.File
	file_internal_integration_infrastructure_api_integration_proto_goTypes = nil
	file_internal_integration_infrastructure_api_integration_proto_depIdxs = nil
}
