api:
  dashboard: true
  insecure: true #development

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: meridian_network
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

log:
  level: DEBUG
  filePath: "/var/log/traefik/traefik.log"
  format: json
